### ISSUE TITLE
Can't compile VS2017 Win32 x86/x64

### ISSUE THREAD

**Issue by c776617** [FlorisCreyf/mp3-decoder#2]
Hi, I commented out `stream()` definition and use in `main.cpp` but that was not enough to make it compile.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"struct <unnamed-type-band_index_table> band_index_table" (?band_index_table@@3U<unnamed-type-band_index_table>@@A) already defined in main.obj	mp3-decoder	Z:\mp3-decoder-master\mp3.obj	1	
Error	LNK2005	"struct <unnamed-type-band_width_table> band_width_table" (?band_width_table@@3U<unnamed-type-band_width_table>@@A) already defined in main.obj	mp3-decoder	Z:\mp3-decoder-master\mp3.obj	1	
Error	LNK2005	"struct <unnamed-type-quad_table_1> quad_table_1" (?quad_table_1@@3U<unnamed-type-quad_table_1>@@A) already defined in main.obj	mp3-decoder	Z:\mp3-decoder-master\mp3.obj	1	
Error	LNK1169	one or more multiply defined symbols found	mp3-decoder	Z:\mp3-decoder-master\Debug\mp3-decoder.exe	1	

```

I'm not experienced enough to be able to solve this. I'm guessing all these are related:

- https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2005)%26rd%3Dtrue
- https://stackoverflow.com/questions/1433204/how-do-i-use-extern-to-share-variables-between-source-files
- https://stackoverflow.com/questions/2125209/linker-errors-even-though-i-prevent-them-with-ifndef

PS: also id3.cpp was causing failure in line 111 `	while (!std::regex_match((string){(char)buffer[i]}, re) && i < size) {`, which I turned into

```
	string istep;
	istep = (char)buffer[0];

	while (!std::regex_match(istep, re) && i < size) {
		istep = (char)buffer[i];
```

**Comment by FlorisCreyf** [comment]
I committed a change that moves the `#include` statements between the `#ifndef` and `#endif` directives. I hope this fixes the problem.

**Comment by c776617** [comment]
Thank you, unfortunately it still fails to compile after I comment out include ALSA, stream() definition and stream() call.

```
1>------ Build started: Project: mp3-decoder, Configuration: Debug x64 ------
1>xing.cpp
1>util.cpp
1>mp3.cpp
1>z:\mp3-decoder-master\mp3.cpp(771): warning C4838: conversion from 'double' to 'const float' requires a narrowing conversion
1>z:\mp3-decoder-master\mp3.cpp(775): warning C4838: conversion from 'double' to 'const float' requires a narrowing conversion
1>main.cpp
1>id3.cpp
1>Generating Code...
1>mp3.obj : error LNK2005: "struct <unnamed-type-band_width_table> band_width_table" (?band_width_table@@3U<unnamed-type-band_width_table>@@A) already defined in main.obj
1>mp3.obj : error LNK2005: "struct <unnamed-type-band_index_table> band_index_table" (?band_index_table@@3U<unnamed-type-band_index_table>@@A) already defined in main.obj
1>mp3.obj : error LNK2005: "struct <unnamed-type-quad_table_1> quad_table_1" (?quad_table_1@@3U<unnamed-type-quad_table_1>@@A) already defined in main.obj
1>z:\mp3-decoder-master\x64\Debug\mp3-decoder.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "mp3-decoder.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I don't understand .h files well but it seems to make sense to me that the #ifndef stuff you did should have helped.

I can compile it in cygwin though (hadn't tried before the latest commit). It relies on some cygwin dlls as a consequence.

Personally I'm just interested in this project to learn about the mp3 format, so I'll just work with cygwin. Maybe someday somebody more experienced with c++ and visual studio will let us know how to fix this.
